### ISSUE TITLE
🌮 The UItimate Taco Recipe 👩‍🍳 (or TACo Application Contracts Checklist)

### ISSUE THREAD

**Issue by cygnusv** [nucypher/nucypher-contracts#101]
Steps labeled with (🤖) are performed by automatic deployment scripts.
Steps labeled with (🫖) depend on Threshold DAO and are outside our control

## 1. State Synchronization Contracts (on Polygon)

- [x] (🤖) `PolygonChild` deployment on Polygon
- [x] (🤖) `TACoChildApplication` implementation deployment on Polygon (with `PolygonChild` as constructor param)
- [x] (🤖) `TACoChildApplication`'s `TransparentUpgradeableProxy` contract deployment
- [x] (🤖) Call `PolygonChild.setChildApplication(tacoChildApp)` on Polygon (this call also renounces ownership of `PolygonChild` on Polygon)
- [x] (🤖) Transfer ownership of `TACoChildApplication`'s `ProxyAdmin` to Threshold Council on Polygon (`0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`)

## 2. TACo app contract (on Mainnet)

- [x] (🤖) TACo app implementation contract deployment
- [x] (🤖) TACo's `TransparentUpgradeableProxy` contract deployment
- [x] (🤖) `PolygonRoot` deployment on Mainnet
- [x] (🤖) Call `TACoApplication.setChildApplication(PolygonRoot)` on Mainnet
- [x] (🤖) Transfer ownership of `TACoApplication` to Threshold Council (`eth:0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`)
- [x] (🤖) Transfer ownership of `TACoApplication`'s `ProxyAdmin` to Threshold Council (`eth:0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`)

## 3. TACo protocol contracts: Coordinator, GlobalAllowList (on Polygon)

- [x] (🤖) Deployment of `Coordinator` contract implementation on Polygon
- [x] (🤖) `Coordinator`'s `TransparentUpgradeableProxy` contract deployment
- [x] (🤖) Transfer ownership of `Coordinator`'s `ProxyAdmin` to Threshold Council on Polygon (`eth:0x9F6e831c8F8939DC0C830C6e492e7cEf4f9C2F5f`)
- [x] (🤖) Grant `TREASURY_ROLE` to Treasury Guild Multisig on Polygon  (`0xc3Bf49eBA094AF346830dF4dbB42a07dE378EeB6`)
- [x] (🤖) Grant `INITIATOR_ROLE` to Integrations Guild (list of address is TBD ‼️ )
- [x] (🤖) Transfer Coordinator admin role to Council by calling `beginDefaultAdminTransfer(council)`
- [x] (🫖) Council accepts admin role in Coordinator by calling `acceptDefaultAdminTransfer()`

## 4. Threshold DAO steps

- [x] (🫖) DAO Snapshot to approve adding TACo app contract 
- [x] (🫖) Council authorizes TACo app as a Threshold staking app

## TODO:
- Audit access control roles, default admins, and owners of TACo contracts
- Consider integration of TACo contracts artifacts as an NPM package

**Comment by jdbertron** [comment]
Not knowing the internal architecture this is confusing. 
Do the automated scripts deploy from contract states/events or from github merges ?
I suppose the information that's relevant to users is the impact NC or the DAO can have on the security of the system. 
Can a revised TACo app compromise the security of existing encrypted payloads, that sort of thing.

**Comment by cygnusv** [comment]
> Not knowing the internal architecture this is confusing. Do the automated scripts deploy from contract states/events or from github merges ? I suppose the information that's relevant to users is the impact NC or the DAO can have on the security of the system. Can a revised TACo app compromise the security of existing encrypted payloads, that sort of thing.

Hey @jdbertron, let me know if the answers in this issue (https://github.com/nucypher/nucypher/issues/3357#issuecomment-1839568399) help you, but TLDR is that contract upgrades or configurations can't compromise the security of encrypted payloads.
